#ifndef BAZA_DATE_H
#define BAZA_DATE_H

#include <vector>
#include <string>

struct Item {
    int id;
    std::string titlu;
    std::vector<std::string> genuri;
    int an;
    double rating;
    std::string tip;
    std::string artist;
    std::string autor;
};

inline std::vector<Item> getBazaDateInitiala() {
    return {
        // ========== FILME (100 itemi, id: 1-100) ==========
        {1, "The Shawshank Redemption", {"Drama", "Crime"}, 1994, 9.3, "film", "", ""},
        {2, "The Godfather", {"Crime", "Drama"}, 1972, 9.2, "film", "", ""},
        {3, "The Dark Knight", {"Action", "Crime", "Drama"}, 2008, 9.0, "film", "", ""},
        {4, "Inception", {"Action", "Sci-Fi", "Thriller"}, 2010, 8.8, "film", "", ""},
        {5, "Interstellar", {"Adventure", "Drama", "Sci-Fi"}, 2014, 8.6, "film", "", ""},
        {6, "Pulp Fiction", {"Crime", "Drama"}, 1994, 8.9, "film", "", ""},
        {7, "The Matrix", {"Action", "Sci-Fi"}, 1999, 8.7, "film", "", ""},
        {8, "Forrest Gump", {"Drama", "Romance"}, 1994, 8.8, "film", "", ""},
        {9, "Goodfellas", {"Crime", "Drama"}, 1990, 8.7, "film", "", ""},
        {10, "The Silence of the Lambs", {"Crime", "Drama", "Thriller"}, 1991, 8.6, "film", "", ""},
        {11, "Saving Private Ryan", {"Drama", "War"}, 1998, 8.6, "film", "", ""},
        {12, "The Green Mile", {"Crime", "Drama", "Fantasy"}, 1999, 8.6, "film", "", ""},
        {13, "Parasite", {"Comedy", "Drama", "Thriller"}, 2019, 8.5, "film", "", ""},
        {14, "The Prestige", {"Drama", "Mystery", "Thriller"}, 2006, 8.5, "film", "", ""},
        {15, "The Departed", {"Crime", "Drama", "Thriller"}, 2006, 8.5, "film", "", ""},
        {16, "Gladiator", {"Action", "Adventure", "Drama"}, 2000, 8.5, "film", "", ""},
        {17, "The Lion King", {"Animation", "Adventure", "Drama"}, 1994, 8.5, "film", "", ""},
        {18, "Terminator 2", {"Action", "Sci-Fi"}, 1991, 8.5, "film", "", ""},
        {19, "Avengers Endgame", {"Action", "Adventure", "Sci-Fi"}, 2019, 8.4, "film", "", ""},
        {20, "Spider-Man No Way Home", {"Action", "Adventure", "Sci-Fi"}, 2021, 8.3, "film", "", ""},
        {21, "Toy Story", {"Animation", "Adventure", "Comedy"}, 1995, 8.3, "film", "", ""},
        {22, "Joker", {"Crime", "Drama", "Thriller"}, 2019, 8.4, "film", "", ""},
        {23, "Dune", {"Action", "Adventure", "Sci-Fi"}, 2021, 8.0, "film", "", ""},
        {24, "Shutter Island", {"Mystery", "Thriller"}, 2010, 8.2, "film", "", ""},
        {25, "The Truman Show", {"Comedy", "Drama", "Sci-Fi"}, 1998, 8.2, "film", "", ""},
        {26, "Fight Club", {"Drama", "Thriller"}, 1999, 8.8, "film", "", ""},
        {27, "The Lord of the Rings: The Return of the King", {"Adventure", "Drama", "Fantasy"}, 2003, 9.0, "film", "", ""},
        {28, "The Lord of the Rings: The Fellowship of the Ring", {"Adventure", "Drama", "Fantasy"}, 2001, 8.8, "film", "", ""},
        {29, "The Lord of the Rings: The Two Towers", {"Adventure", "Drama", "Fantasy"}, 2002, 8.8, "film", "", ""},
        {30, "Schindler's List", {"Biography", "Drama", "History"}, 1993, 9.0, "film", "", ""},
        {31, "12 Angry Men", {"Crime", "Drama"}, 1957, 9.0, "film", "", ""},
        {32, "The Usual Suspects", {"Crime", "Mystery", "Thriller"}, 1995, 8.5, "film", "", ""},
        {33, "Se7en", {"Crime", "Drama", "Mystery"}, 1995, 8.6, "film", "", ""},
        {34, "City of God", {"Crime", "Drama"}, 2002, 8.6, "film", "", ""},
        {35, "Life is Beautiful", {"Comedy", "Drama", "Romance"}, 1997, 8.6, "film", "", ""},
        {36, "The Sixth Sense", {"Drama", "Mystery", "Thriller"}, 1999, 8.2, "film", "", ""},
        {37, "Memento", {"Mystery", "Thriller"}, 2000, 8.4, "film", "", ""},
        {38, "The Pianist", {"Biography", "Drama", "Music"}, 2002, 8.5, "film", "", ""},
        {39, "Whiplash", {"Drama", "Music"}, 2014, 8.5, "film", "", ""},
        {40, "The Intouchables", {"Biography", "Comedy", "Drama"}, 2011, 8.5, "film", "", ""},
        {41, "The Social Network", {"Biography", "Drama"}, 2010, 7.8, "film", "", ""},
        {42, "Django Unchained", {"Drama", "Western"}, 2012, 8.4, "film", "", ""},
        {43, "Inglourious Basterds", {"Adventure", "Drama", "War"}, 2009, 8.3, "film", "", ""},
        {44, "The Grand Budapest Hotel", {"Adventure", "Comedy", "Crime"}, 2014, 8.1, "film", "", ""},
        {45, "Mad Max Fury Road", {"Action", "Adventure", "Sci-Fi"}, 2015, 8.1, "film", "", ""},
        {46, "Blade Runner 2049", {"Action", "Drama", "Mystery"}, 2017, 8.0, "film", "", ""},
        {47, "Arrival", {"Drama", "Mystery", "Sci-Fi"}, 2016, 7.9, "film", "", ""},
        {48, "Ex Machina", {"Drama", "Sci-Fi", "Thriller"}, 2014, 7.7, "film", "", ""},
        {49, "Her", {"Drama", "Romance", "Sci-Fi"}, 2013, 8.0, "film", "", ""},
        {50, "Eternal Sunshine of the Spotless Mind", {"Drama", "Romance", "Sci-Fi"}, 2004, 8.3, "film", "", ""},
        {51, "Black Swan", {"Drama", "Thriller"}, 2010, 8.0, "film", "", ""},
        {52, "Requiem for a Dream", {"Drama"}, 2000, 8.3, "film", "", ""},
        {53, "American Beauty", {"Drama"}, 1999, 8.3, "film", "", ""},
        {54, "Good Will Hunting", {"Drama", "Romance"}, 1997, 8.3, "film", "", ""},
        {55, "The Breakfast Club", {"Comedy", "Drama"}, 1985, 7.8, "film", "", ""},
        {56, "Dead Poets Society", {"Comedy", "Drama"}, 1989, 8.1, "film", "", ""},
        {57, "A Beautiful Mind", {"Biography", "Drama"}, 2001, 8.2, "film", "", ""},
        {58, "The Theory of Everything", {"Biography", "Drama", "Romance"}, 2014, 7.7, "film", "", ""},
        {59, "The Imitation Game", {"Biography", "Drama", "Thriller"}, 2014, 8.0, "film", "", ""},
        {60, "12 Years a Slave", {"Biography", "Drama", "History"}, 2013, 8.1, "film", "", ""},
        {61, "Lincoln", {"Biography", "Drama", "History"}, 2012, 7.3, "film", "", ""},
        {62, "Spotlight", {"Biography", "Crime", "Drama"}, 2015, 8.1, "film", "", ""},
        {63, "The Big Short", {"Biography", "Comedy", "Drama"}, 2015, 7.8, "film", "", ""},
        {64, "Moneyball", {"Biography", "Drama", "Sport"}, 2011, 7.6, "film", "", ""},
        {65, "Rocky", {"Drama", "Sport"}, 1976, 8.1, "film", "", ""},
        {66, "Creed", {"Drama", "Sport"}, 2015, 7.6, "film", "", ""},
        {67, "Raging Bull", {"Biography", "Drama", "Sport"}, 1980, 8.2, "film", "", ""},
        {68, "The Wrestler", {"Drama", "Sport"}, 2008, 7.9, "film", "", ""},
        {69, "Million Dollar Baby", {"Drama", "Sport"}, 2004, 8.1, "film", "", ""},
        {70, "The Shining", {"Drama", "Horror"}, 1980, 8.4, "film", "", ""},
        {71, "The Exorcist", {"Horror"}, 1973, 8.1, "film", "", ""},
        {72, "Get Out", {"Horror", "Mystery", "Thriller"}, 2017, 7.7, "film", "", ""},
        {73, "A Quiet Place", {"Drama", "Horror", "Sci-Fi"}, 2018, 7.5, "film", "", ""},
        {74, "Hereditary", {"Drama", "Horror", "Mystery"}, 2018, 7.3, "film", "", ""},
        {75, "The Conjuring", {"Horror", "Mystery", "Thriller"}, 2013, 7.5, "film", "", ""},
        {76, "It", {"Horror"}, 2017, 7.3, "film", "", ""},
        {77, "The Witch", {"Drama", "Fantasy", "Horror"}, 2015, 7.0, "film", "", ""},
        {78, "Midsommar", {"Drama", "Horror", "Mystery"}, 2019, 7.1, "film", "", ""},
        {79, "Us", {"Horror", "Mystery", "Thriller"}, 2019, 6.8, "film", "", ""},
        {80, "Jaws", {"Adventure", "Mystery", "Thriller"}, 1975, 8.1, "film", "", ""},
        {81, "Alien", {"Horror", "Sci-Fi"}, 1979, 8.5, "film", "", ""},
        {82, "Aliens", {"Action", "Adventure", "Sci-Fi"}, 1986, 8.4, "film", "", ""},
        {83, "Predator", {"Action", "Adventure", "Horror"}, 1987, 7.8, "film", "", ""},
        {84, "The Thing", {"Horror", "Mystery", "Sci-Fi"}, 1982, 8.2, "film", "", ""},
        {85, "Back to the Future", {"Adventure", "Comedy", "Sci-Fi"}, 1985, 8.5, "film", "", ""},
        {86, "Jurassic Park", {"Action", "Adventure", "Sci-Fi"}, 1993, 8.2, "film", "", ""},
        {87, "E.T. the Extra-Terrestrial", {"Family", "Sci-Fi"}, 1982, 7.9, "film", "", ""},
        {88, "Star Wars Episode V", {"Action", "Adventure", "Fantasy"}, 1980, 8.7, "film", "", ""},
        {89, "Star Wars Episode IV", {"Action", "Adventure", "Fantasy"}, 1977, 8.6, "film", "", ""},
        {90, "Indiana Jones and the Raiders of the Lost Ark", {"Action", "Adventure"}, 1981, 8.4, "film", "", ""},
        {91, "Die Hard", {"Action", "Thriller"}, 1988, 8.2, "film", "", ""},
        {92, "Lethal Weapon", {"Action", "Crime", "Thriller"}, 1987, 7.6, "film", "", ""},
        {93, "Mad Max", {"Action", "Adventure", "Sci-Fi"}, 1979, 6.8, "film", "", ""},
        {94, "The Terminator", {"Action", "Sci-Fi"}, 1984, 8.1, "film", "", ""},
        {95, "RoboCop", {"Action", "Crime", "Sci-Fi"}, 1987, 7.6, "film", "", ""},
        {96, "Total Recall", {"Action", "Adventure", "Sci-Fi"}, 1990, 7.5, "film", "", ""},
        {97, "The Fifth Element", {"Action", "Adventure", "Sci-Fi"}, 1997, 7.6, "film", "", ""},
        {98, "Blade Runner", {"Action", "Drama", "Sci-Fi"}, 1982, 8.1, "film", "", ""},
        {99, "2001 A Space Odyssey", {"Adventure", "Sci-Fi"}, 1968, 8.3, "film", "", ""},
        {100, "Interstellar", {"Adventure", "Drama", "Sci-Fi"}, 2014, 8.7, "film", "", ""},

        // ========== CĂRȚI (100 itemi, id: 101-200) ==========
        {101, "1984", {"Fiction", "Dystopian", "Political"}, 1949, 9.1, "carte", "", "George Orwell"},
        {102, "To Kill a Mockingbird", {"Fiction", "Drama", "Legal"}, 1960, 8.9, "carte", "", "Harper Lee"},
        {103, "The Great Gatsby", {"Fiction", "Tragedy", "Romance"}, 1925, 8.7, "carte", "", "F. Scott Fitzgerald"},
        {104, "Harry Potter and the Sorcerer's Stone", {"Fantasy", "Adventure", "Young Adult"}, 1997, 8.8, "carte", "", "J.K. Rowling"},
        {105, "The Lord of the Rings", {"Fantasy", "Adventure", "Epic"}, 1954, 9.5, "carte", "", "J.R.R. Tolkien"},
        {106, "Pride and Prejudice", {"Romance", "Fiction", "Classic"}, 1813, 8.8, "carte", "", "Jane Austen"},
        {107, "The Catcher in the Rye", {"Fiction", "Coming-of-Age"}, 1951, 8.3, "carte", "", "J.D. Salinger"},
        {108, "The Hobbit", {"Fantasy", "Adventure"}, 1937, 8.9, "carte", "", "J.R.R. Tolkien"},
        {109, "Fahrenheit 451", {"Science Fiction", "Dystopian"}, 1953, 8.5, "carte", "", "Ray Bradbury"},
        {110, "Brave New World", {"Science Fiction", "Dystopian"}, 1932, 8.4, "carte", "", "Aldous Huxley"},
        {111, "The Chronicles of Narnia", {"Fantasy", "Adventure", "Children"}, 1950, 8.7, "carte", "", "C.S. Lewis"},
        {112, "Dune", {"Science Fiction", "Adventure"}, 1965, 8.8, "carte", "", "Frank Herbert"},
        {113, "The Hunger Games", {"Science Fiction", "Dystopian", "Young Adult"}, 2008, 8.1, "carte", "", "Suzanne Collins"},
        {114, "Gone Girl", {"Mystery", "Thriller", "Psychological"}, 2012, 8.3, "carte", "", "Gillian Flynn"},
        {115, "The Da Vinci Code", {"Mystery", "Thriller"}, 2003, 7.9, "carte", "", "Dan Brown"},
        {116, "The Alchemist", {"Fiction", "Philosophy", "Adventure"}, 1988, 8.6, "carte", "", "Paulo Coelho"},
        {117, "Life of Pi", {"Adventure", "Fiction", "Fantasy"}, 2001, 8.2, "carte", "", "Yann Martel"},
        {118, "The Book Thief", {"Historical Fiction", "War", "Drama"}, 2005, 8.7, "carte", "", "Markus Zusak"},
        {119, "The Kite Runner", {"Fiction", "Drama", "Historical"}, 2003, 8.5, "carte", "", "Khaled Hosseini"},
        {120, "A Game of Thrones", {"Fantasy", "Epic", "Political"}, 1996, 8.9, "carte", "", "George R.R. Martin"},
        {121, "The Girl with the Dragon Tattoo", {"Mystery", "Thriller", "Crime"}, 2005, 8.4, "carte", "", "Stieg Larsson"},
        {122, "The Road", {"Post-Apocalyptic", "Fiction", "Drama"}, 2006, 8.3, "carte", "", "Cormac McCarthy"},
        {123, "Sapiens", {"Non-fiction", "History", "Science"}, 2011, 9.0, "carte", "", "Yuval Noah Harari"},
        {124, "Educated", {"Memoir", "Non-fiction", "Biography"}, 2018, 8.8, "carte", "", "Tara Westover"},
        {125, "Atomic Habits", {"Self-help", "Non-fiction", "Psychology"}, 2018, 8.7, "carte", "", "James Clear"},
        {126, "Animal Farm", {"Fiction", "Satire", "Political"}, 1945, 8.9, "carte", "", "George Orwell"},
        {127, "Lord of the Flies", {"Fiction", "Adventure", "Dystopian"}, 1954, 8.2, "carte", "", "William Golding"},
        {128, "Slaughterhouse-Five", {"Fiction", "Science Fiction", "War"}, 1969, 8.4, "carte", "", "Kurt Vonnegut"},
        {129, "One Hundred Years of Solitude", {"Fiction", "Magical Realism"}, 1967, 8.8, "carte", "", "Gabriel García Márquez"},
        {130, "Moby-Dick", {"Fiction", "Adventure", "Classic"}, 1851, 8.3, "carte", "", "Herman Melville"},
        {131, "The Grapes of Wrath", {"Fiction", "Historical", "Drama"}, 1939, 8.5, "carte", "", "John Steinbeck"},
        {132, "Of Mice and Men", {"Fiction", "Tragedy"}, 1937, 8.3, "carte", "", "John Steinbeck"},
        {133, "Brave New World Revisited", {"Non-fiction", "Philosophy"}, 1958, 8.0, "carte", "", "Aldous Huxley"},
        {134, "The Handmaid's Tale", {"Fiction", "Dystopian", "Feminist"}, 1985, 8.6, "carte", "", "Margaret Atwood"},
        {135, "The Bell Jar", {"Fiction", "Autobiography", "Psychology"}, 1963, 8.1, "carte", "", "Sylvia Plath"},
        {136, "Wuthering Heights", {"Romance", "Gothic", "Classic"}, 1847, 8.2, "carte", "", "Emily Brontë"},
        {137, "Jane Eyre", {"Romance", "Gothic", "Classic"}, 1847, 8.5, "carte", "", "Charlotte Brontë"},
        {138, "Great Expectations", {"Fiction", "Coming-of-Age", "Classic"}, 1861, 8.3, "carte", "", "Charles Dickens"},
        {139, "A Tale of Two Cities", {"Fiction", "Historical", "Classic"}, 1859, 8.4, "carte", "", "Charles Dickens"},
        {140, "The Picture of Dorian Gray", {"Fiction", "Gothic", "Philosophy"}, 1890, 8.5, "carte", "", "Oscar Wilde"},
        {141, "Frankenstein", {"Fiction", "Gothic", "Science Fiction"}, 1818, 8.3, "carte", "", "Mary Shelley"},
        {142, "Dracula", {"Fiction", "Gothic", "Horror"}, 1897, 8.4, "carte", "", "Bram Stoker"},
        {143, "The Strange Case of Dr Jekyll and Mr Hyde", {"Fiction", "Gothic", "Horror"}, 1886, 8.2, "carte", "", "Robert Louis Stevenson"},
        {144, "The Count of Monte Cristo", {"Fiction", "Adventure", "Historical"}, 1844, 9.0, "carte", "", "Alexandre Dumas"},
        {145, "The Three Musketeers", {"Fiction", "Adventure", "Historical"}, 1844, 8.6, "carte", "", "Alexandre Dumas"},
        {146, "Crime and Punishment", {"Fiction", "Psychological", "Philosophical"}, 1866, 9.1, "carte", "", "Fyodor Dostoevsky"},
        {147, "The Brothers Karamazov", {"Fiction", "Philosophical", "Drama"}, 1880, 9.2, "carte", "", "Fyodor Dostoevsky"},
        {148, "War and Peace", {"Fiction", "Historical", "Epic"}, 1869, 9.3, "carte", "", "Leo Tolstoy"},
        {149, "Anna Karenina", {"Fiction", "Romance", "Tragedy"}, 1877, 9.0, "carte", "", "Leo Tolstoy"},
        {150, "The Odyssey", {"Epic", "Adventure", "Mythology"}, -800, 8.7, "carte", "", "Homer"},
        {151, "The Iliad", {"Epic", "War", "Mythology"}, -750, 8.6, "carte", "", "Homer"},
        {152, "The Divine Comedy", {"Epic", "Poetry", "Religion"}, 1320, 8.8, "carte", "", "Dante Alighieri"},
        {153, "Don Quixote", {"Fiction", "Adventure", "Satire"}, 1605, 8.7, "carte", "", "Miguel de Cervantes"},
        {154, "Ulysses", {"Fiction", "Modernist"}, 1922, 8.4, "carte", "", "James Joyce"},
        {155, "Catch-22", {"Fiction", "Satire", "War"}, 1961, 8.5, "carte", "", "Joseph Heller"},
        {156, "The Sound and the Fury", {"Fiction", "Modernist", "Southern Gothic"}, 1929, 8.3, "carte", "", "William Faulkner"},
        {157, "Beloved", {"Fiction", "Historical", "Gothic"}, 1987, 8.6, "carte", "", "Toni Morrison"},
        {158, "Invisible Man", {"Fiction", "Social Commentary"}, 1952, 8.5, "carte", "", "Ralph Ellison"},
        {159, "The Color Purple", {"Fiction", "Epistolary", "Historical"}, 1982, 8.4, "carte", "", "Alice Walker"},
        {160, "Their Eyes Were Watching God", {"Fiction", "Romance", "Historical"}, 1937, 8.3, "carte", "", "Zora Neale Hurston"},
        {161, "Middlesex", {"Fiction", "Coming-of-Age", "LGBTQ"}, 2002, 8.2, "carte", "", "Jeffrey Eugenides"},
        {162, "The Amazing Adventures of Kavalier & Clay", {"Fiction", "Historical"}, 2000, 8.4, "carte", "", "Michael Chabon"},
        {163, "Cloud Atlas", {"Fiction", "Science Fiction", "Historical"}, 2004, 8.3, "carte", "", "David Mitchell"},
        {164, "Never Let Me Go", {"Fiction", "Science Fiction", "Dystopian"}, 2005, 8.1, "carte", "", "Kazuo Ishiguro"},
        {165, "The Remains of the Day", {"Fiction", "Historical"}, 1989, 8.4, "carte", "", "Kazuo Ishiguro"},
        {166, "Norwegian Wood", {"Fiction", "Romance", "Coming-of-Age"}, 1987, 8.2, "carte", "", "Haruki Murakami"},
        {167, "Kafka on the Shore", {"Fiction", "Magical Realism", "Surreal"}, 2002, 8.3, "carte", "", "Haruki Murakami"},
        {168, "1Q84", {"Fiction", "Dystopian", "Surreal"}, 2009, 8.0, "carte", "", "Haruki Murakami"},
        {169, "The Wind-Up Bird Chronicle", {"Fiction", "Surreal", "Mystery"}, 1994, 8.2, "carte", "", "Haruki Murakami"},
        {170, "The Name of the Rose", {"Fiction", "Historical", "Mystery"}, 1980, 8.5, "carte", "", "Umberto Eco"},
        {171, "The Shadow of the Wind", {"Fiction", "Mystery", "Gothic"}, 2001, 8.6, "carte", "", "Carlos Ruiz Zafón"},
        {172, "The Night Circus", {"Fiction", "Fantasy", "Romance"}, 2011, 8.1, "carte", "", "Erin Morgenstern"},
        {173, "The Ocean at the End of the Lane", {"Fiction", "Fantasy", "Dark Fantasy"}, 2013, 8.0, "carte", "", "Neil Gaiman"},
        {174, "American Gods", {"Fiction", "Fantasy", "Contemporary Fantasy"}, 2001, 8.3, "carte", "", "Neil Gaiman"},
        {175, "Good Omens", {"Fiction", "Fantasy", "Comedy"}, 1990, 8.4, "carte", "", "Neil Gaiman & Terry Pratchett"},
        {176, "The Hitchhiker's Guide to the Galaxy", {"Fiction", "Science Fiction", "Comedy"}, 1979, 8.6, "carte", "", "Douglas Adams"},
        {177, "Foundation", {"Science Fiction", "Space Opera"}, 1951, 8.7, "carte", "", "Isaac Asimov"},
        {178, "I Robot", {"Science Fiction", "Short Stories"}, 1950, 8.5, "carte", "", "Isaac Asimov"},
        {179, "Neuromancer", {"Science Fiction", "Cyberpunk"}, 1984, 8.4, "carte", "", "William Gibson"},
        {180, "Snow Crash", {"Science Fiction", "Cyberpunk"}, 1992, 8.2, "carte", "", "Neal Stephenson"},
        {181, "The Martian", {"Science Fiction", "Survival"}, 2011, 8.6, "carte", "", "Andy Weir"},
        {182, "Project Hail Mary", {"Science Fiction", "Space"}, 2021, 8.8, "carte", "", "Andy Weir"},
        {183, "Ready Player One", {"Science Fiction", "Dystopian", "Adventure"}, 2011, 7.9, "carte", "", "Ernest Cline"},
        {184, "Ender's Game", {"Science Fiction", "Military", "Young Adult"}, 1985, 8.6, "carte", "", "Orson Scott Card"},
        {185, "The Left Hand of Darkness", {"Science Fiction", "Feminist"}, 1969, 8.4, "carte", "", "Ursula K. Le Guin"},
        {186, "A Wizard of Earthsea", {"Fantasy", "Coming-of-Age"}, 1968, 8.5, "carte", "", "Ursula K. Le Guin"},
        {187, "The Name of the Wind", {"Fantasy", "Adventure"}, 2007, 8.7, "carte", "", "Patrick Rothfuss"},
        {188, "Mistborn The Final Empire", {"Fantasy", "Epic"}, 2006, 8.6, "carte", "", "Brandon Sanderson"},
        {189, "The Way of Kings", {"Fantasy", "Epic"}, 2010, 8.8, "carte", "", "Brandon Sanderson"},
        {190, "The Eye of the World", {"Fantasy", "Epic"}, 1990, 8.4, "carte", "", "Robert Jordan"},
        {191, "The Lies of Locke Lamora", {"Fantasy", "Heist"}, 2006, 8.5, "carte", "", "Scott Lynch"},
        {192, "The Fifth Season", {"Fantasy", "Science Fiction", "Post-Apocalyptic"}, 2015, 8.3, "carte", "", "N.K. Jemisin"},
        {193, "Circe", {"Fiction", "Fantasy", "Mythology"}, 2018, 8.5, "carte", "", "Madeline Miller"},
        {194, "The Song of Achilles", {"Fiction", "Historical", "Mythology"}, 2011, 8.7, "carte", "", "Madeline Miller"},
        {195, "Thinking Fast and Slow", {"Non-fiction", "Psychology", "Science"}, 2011, 8.6, "carte", "", "Daniel Kahneman"},
        {196, "The Power of Habit", {"Non-fiction", "Self-help", "Psychology"}, 2012, 8.3, "carte", "", "Charles Duhigg"},
        {197, "Quiet The Power of Introverts", {"Non-fiction", "Psychology", "Self-help"}, 2012, 8.4, "carte", "", "Susan Cain"},
        {198, "Man's Search for Meaning", {"Non-fiction", "Memoir", "Philosophy"}, 1946, 9.2, "carte", "", "Viktor E. Frankl"},
        {199, "The Subtle Art of Not Giving", {"Non-fiction", "Self-help", "Philosophy"}, 2016, 7.8, "carte", "", "Mark Manson"},
        {200, "Born a Crime", {"Non-fiction", "Memoir", "Biography"}, 2016, 8.7, "carte", "", "Trevor Noah"},

        // ========== MUZICĂ (100 itemi, id: 201-300) ==========
        {201, "Bohemian Rhapsody", {"Rock", "Progressive", "Opera"}, 1975, 9.4, "muzica", "Queen", ""},
        {202, "Hotel California", {"Rock", "Soft Rock"}, 1976, 9.0, "muzica", "Eagles", ""},
        {203, "Imagine", {"Pop", "Soft Rock"}, 1971, 8.9, "muzica", "John Lennon", ""},
        {204, "Stairway to Heaven", {"Rock", "Hard Rock", "Progressive"}, 1971, 9.3, "muzica", "Led Zeppelin", ""},
        {205, "Smells Like Teen Spirit", {"Grunge", "Alternative Rock"}, 1991, 8.8, "muzica", "Nirvana", ""},
        {206, "Hey Jude", {"Rock", "Pop"}, 1968, 9.1, "muzica", "The Beatles", ""},
        {207, "Sweet Child O' Mine", {"Hard Rock", "Rock"}, 1987, 8.9, "muzica", "Guns N' Roses", ""},
        {208, "Billie Jean", {"Pop", "R&B"}, 1982, 9.0, "muzica", "Michael Jackson", ""},
        {209, "Like a Rolling Stone", {"Rock", "Folk Rock"}, 1965, 8.8, "muzica", "Bob Dylan", ""},
        {210, "Purple Haze", {"Rock", "Psychedelic"}, 1967, 8.7, "muzica", "Jimi Hendrix", ""},
        {211, "What's Going On", {"Soul", "R&B"}, 1971, 8.9, "muzica", "Marvin Gaye", ""},
        {212, "Respect", {"Soul", "R&B"}, 1967, 8.8, "muzica", "Aretha Franklin", ""},
        {213, "One", {"Rock", "Alternative"}, 1991, 8.6, "muzica", "U2", ""},
        {214, "Lose Yourself", {"Hip-Hop", "Rap"}, 2002, 8.7, "muzica", "Eminem", ""},
        {215, "Wonderwall", {"Rock", "Britpop"}, 1995, 8.5, "muzica", "Oasis", ""},
        {216, "Shape of You", {"Pop", "Dance"}, 2017, 8.2, "muzica", "Ed Sheeran", ""},
        {217, "Rolling in the Deep", {"Pop", "Soul"}, 2010, 8.6, "muzica", "Adele", ""},
        {218, "Uptown Funk", {"Funk", "Pop"}, 2014, 8.4, "muzica", "Mark Ronson ft. Bruno Mars", ""},
        {219, "Blinding Lights", {"Synthwave", "Pop"}, 2019, 8.5, "muzica", "The Weeknd", ""},
        {220, "Take Five", {"Jazz", "Cool Jazz"}, 1959, 8.8, "muzica", "Dave Brubeck", ""},
        {221, "Clair de Lune", {"Classical", "Impressionist"}, 1905, 9.2, "muzica", "Claude Debussy", ""},
        {222, "Für Elise", {"Classical", "Romantic"}, 1810, 9.0, "muzica", "Ludwig van Beethoven", ""},
        {223, "Strobe", {"Electronic", "Progressive House"}, 2009, 8.7, "muzica", "Deadmau5", ""},
        {224, "Midnight City", {"Electronic", "Synthpop"}, 2011, 8.5, "muzica", "M83", ""},
        {225, "Levels", {"Electronic", "House"}, 2011, 8.6, "muzica", "Avicii", ""},
        {226, "Yesterday", {"Pop", "Rock"}, 1965, 9.0, "muzica", "The Beatles", ""},
        {227, "Let It Be", {"Rock", "Pop"}, 1970, 8.9, "muzica", "The Beatles", ""},
        {228, "Come Together", {"Rock", "Blues"}, 1969, 8.7, "muzica", "The Beatles", ""},
        {229, "A Day in the Life", {"Rock", "Psychedelic"}, 1967, 9.1, "muzica", "The Beatles", ""},
        {230, "While My Guitar Gently Weeps", {"Rock", "Blues"}, 1968, 8.8, "muzica", "The Beatles", ""},
        {231, "Comfortably Numb", {"Rock", "Progressive"}, 1979, 9.2, "muzica", "Pink Floyd", ""},
        {232, "Wish You Were Here", {"Rock", "Progressive"}, 1975, 9.0, "muzica", "Pink Floyd", ""},
        {233, "Another Brick in the Wall", {"Rock", "Progressive"}, 1979, 8.8, "muzica", "Pink Floyd", ""},
        {234, "Time", {"Rock", "Progressive"}, 1973, 8.9, "muzica", "Pink Floyd", ""},
        {235, "Money", {"Rock", "Progressive"}, 1973, 8.7, "muzica", "Pink Floyd", ""},
        {236, "Shine On You Crazy Diamond", {"Rock", "Progressive"}, 1975, 9.1, "muzica", "Pink Floyd", ""},
        {237, "Kashmir", {"Rock", "Hard Rock"}, 1975, 8.9, "muzica", "Led Zeppelin", ""},
        {238, "Whole Lotta Love", {"Rock", "Hard Rock"}, 1969, 8.7, "muzica", "Led Zeppelin", ""},
        {239, "Black Dog", {"Rock", "Hard Rock"}, 1971, 8.6, "muzica", "Led Zeppelin", ""},
        {240, "Immigrant Song", {"Rock", "Hard Rock"}, 1970, 8.5, "muzica", "Led Zeppelin", ""},
        {241, "We Will Rock You", {"Rock", "Anthem"}, 1977, 8.8, "muzica", "Queen", ""},
        {242, "Don't Stop Me Now", {"Rock", "Pop"}, 1978, 8.9, "muzica", "Queen", ""},
        {243, "Somebody to Love", {"Rock", "Gospel"}, 1976, 8.7, "muzica", "Queen", ""},
        {244, "Under Pressure", {"Rock", "Pop"}, 1981, 8.8, "muzica", "Queen & David Bowie", ""},
        {245, "Love of My Life", {"Rock", "Ballad"}, 1975, 8.6, "muzica", "Queen", ""},
        {246, "Heroes", {"Rock", "Art Rock"}, 1977, 8.9, "muzica", "David Bowie", ""},
        {247, "Space Oddity", {"Rock", "Art Rock"}, 1969, 8.7, "muzica", "David Bowie", ""},
        {248, "Life on Mars", {"Rock", "Glam Rock"}, 1971, 8.8, "muzica", "David Bowie", ""},
        {249, "Starman", {"Rock", "Glam Rock"}, 1972, 8.6, "muzica", "David Bowie", ""},
        {250, "Changes", {"Rock", "Glam Rock"}, 1971, 8.5, "muzica", "David Bowie", ""},
        {251, "Thriller", {"Pop", "Funk"}, 1982, 9.1, "muzica", "Michael Jackson", ""},
        {252, "Beat It", {"Pop", "Rock"}, 1982, 8.9, "muzica", "Michael Jackson", ""},
        {253, "Smooth Criminal", {"Pop", "Funk"}, 1987, 8.8, "muzica", "Michael Jackson", ""},
        {254, "Black or White", {"Pop", "Rock"}, 1991, 8.6, "muzica", "Michael Jackson", ""},
        {255, "Man in the Mirror", {"Pop", "Soul"}, 1987, 8.7, "muzica", "Michael Jackson", ""},
        {256, "Purple Rain", {"Rock", "Pop"}, 1984, 9.0, "muzica", "Prince", ""},
        {257, "When Doves Cry", {"Pop", "Funk"}, 1984, 8.8, "muzica", "Prince", ""},
        {258, "Kiss", {"Pop", "Funk"}, 1986, 8.6, "muzica", "Prince", ""},
        {259, "1999", {"Pop", "Funk"}, 1982, 8.5, "muzica", "Prince", ""},
        {260, "Little Red Corvette", {"Pop", "Rock"}, 1982, 8.4, "muzica", "Prince", ""},
        {261, "Dream On", {"Rock", "Hard Rock"}, 1973, 8.7, "muzica", "Aerosmith", ""},
        {262, "Walk This Way", {"Rock", "Hard Rock"}, 1975, 8.5, "muzica", "Aerosmith", ""},
        {263, "I Don't Want to Miss a Thing", {"Rock", "Ballad"}, 1998, 8.4, "muzica", "Aerosmith", ""},
        {264, "Enter Sandman", {"Metal", "Heavy Metal"}, 1991, 8.8, "muzica", "Metallica", ""},
        {265, "Nothing Else Matters", {"Metal", "Ballad"}, 1991, 8.9, "muzica", "Metallica", ""},
        {266, "Master of Puppets", {"Metal", "Thrash Metal"}, 1986, 9.0, "muzica", "Metallica", ""},
        {267, "One", {"Metal", "Thrash Metal"}, 1988, 8.9, "muzica", "Metallica", ""},
        {268, "The Unforgiven", {"Metal", "Heavy Metal"}, 1991, 8.6, "muzica", "Metallica", ""},
        {269, "November Rain", {"Rock", "Ballad"}, 1991, 8.9, "muzica", "Guns N' Roses", ""},
        {270, "Paradise City", {"Rock", "Hard Rock"}, 1987, 8.7, "muzica", "Guns N' Roses", ""},
        {271, "Welcome to the Jungle", {"Rock", "Hard Rock"}, 1987, 8.8, "muzica", "Guns N' Roses", ""},
        {272, "Don't Cry", {"Rock", "Ballad"}, 1991, 8.5, "muzica", "Guns N' Roses", ""},
        {273, "Patience", {"Rock", "Ballad"}, 1988, 8.6, "muzica", "Guns N' Roses", ""},
        {274, "Every Breath You Take", {"Pop", "Rock"}, 1983, 8.7, "muzica", "The Police", ""},
        {275, "Message in a Bottle", {"Rock", "New Wave"}, 1979, 8.5, "muzica", "The Police", ""},
        {276, "Roxanne", {"Rock", "Reggae"}, 1978, 8.4, "muzica", "The Police", ""},
        {277, "Summer of '69", {"Rock", "Pop"}, 1984, 8.6, "muzica", "Bryan Adams", ""},
        {278, "Living on a Prayer", {"Rock", "Pop"}, 1986, 8.7, "muzica", "Bon Jovi", ""},
        {279, "You Give Love a Bad Name", {"Rock", "Pop"}, 1986, 8.5, "muzica", "Bon Jovi", ""},
        {280, "With or Without You", {"Rock", "Alternative"}, 1987, 8.8, "muzica", "U2", ""},
        {281, "Where the Streets Have No Name", {"Rock", "Alternative"}, 1987, 8.7, "muzica", "U2", ""},
        {282, "Beautiful Day", {"Rock", "Alternative"}, 2000, 8.5, "muzica", "U2", ""},
        {283, "Creep", {"Alternative Rock", "Grunge"}, 1992, 8.6, "muzica", "Radiohead", ""},
        {284, "Karma Police", {"Alternative Rock"}, 1997, 8.7, "muzica", "Radiohead", ""},
        {285, "No Surprises", {"Alternative Rock"}, 1997, 8.5, "muzica", "Radiohead", ""},
        {286, "Paranoid Android", {"Alternative Rock", "Progressive"}, 1997, 8.8, "muzica", "Radiohead", ""},
        {287, "Fake Plastic Trees", {"Alternative Rock"}, 1995, 8.4, "muzica", "Radiohead", ""},
        {288, "Mr. Brightside", {"Alternative Rock", "Indie"}, 2003, 8.6, "muzica", "The Killers", ""},
        {289, "Somebody That I Used to Know", {"Indie Pop", "Alternative"}, 2011, 8.3, "muzica", "Gotye", ""},
        {290, "Pumped Up Kicks", {"Indie Pop", "Alternative"}, 2010, 8.2, "muzica", "Foster the People", ""},
        {291, "Take On Me", {"Synthpop", "New Wave"}, 1984, 8.6, "muzica", "a-ha", ""},
        {292, "Tainted Love", {"Synthpop", "New Wave"}, 1981, 8.4, "muzica", "Soft Cell", ""},
        {293, "Blue Monday", {"Electronic", "New Wave"}, 1983, 8.5, "muzica", "New Order", ""},
        {294, "Sweet Dreams", {"Synthpop", "New Wave"}, 1983, 8.6, "muzica", "Eurythmics", ""},
        {295, "Don't You Forget About Me", {"Rock", "New Wave"}, 1985, 8.5, "muzica", "Simple Minds", ""},
        {296, "Africa", {"Pop", "Rock"}, 1982, 8.8, "muzica", "Toto", ""},
        {297, "Rosanna", {"Pop", "Rock"}, 1982, 8.5, "muzica", "Toto", ""},
        {298, "Hold the Line", {"Rock", "Pop"}, 1978, 8.4, "muzica", "Toto", ""},
        {299, "In the Air Tonight", {"Pop", "Rock"}, 1981, 8.7, "muzica", "Phil Collins", ""},
        {300, "Against All Odds", {"Pop", "Ballad"}, 1984, 8.6, "muzica", "Phil Collins", ""}
    };
}

#endif // BAZA_DATE_H